app/__init__.py
from flask import Flask
from flask_sqlalchemy import SQLAlchemy

db = SQLAlchemy()

def creat_app():

    app = Flask(__name__)

    app.config['SECRET_KEY'] = 'MY_SECRET_KEY'
    app.config['SQLALCHEMY_DATABASE_URI'] = 'sqlite:///database.db'
    app.config['SQLALCHEMY_TRACK_MODIFICATION'] = False

    db.__init__(app)

    from app.modules import Task

    with app.app_context():
        
        db.create_all()


    from app.routes.auths import auth_bp
    from app.routes.tasks import task_bp
    app.register_blueprint(auth_bp)
    app.register_blueprint(task_bp)

    return app

    

app/routes/auths.py
from flask import Flask, Blueprint, redirect, render_template, url_for, request, flash, session as login_session
from app.modules import UserInformation
from app import db

auth_bp = Blueprint("auth", __name__)

@auth_bp.route('/login', methods = ["POST", "GET"])
def login():
    
    if request.method == "POST":

        username = request.form.get("username")
        user = UserInformation.query.filter_by(name = username).first()

        if user:

            login_session["username"] = user.name
            flash('Login successfuly!', 'success')
            return redirect(url_for('task.view_task'))
        
        flash("Invalid Credential!", "denger")
        # return render_template("login.html")
    
    return render_template("login.html")


@auth_bp.route('/register', methods = ["POST", "GET"])
def register():
    if request.method == "POST":

        username = request.form.get("username")
        user = UserInformation.query.filter_by(name = username).first()
        if user:
            flash('user alredy exist! choose another username', 'denger')
            return render_template('register.html')
        
        password = request.form.get("password")
        email = request.form.get("email")

        new_user = UserInformation(name = username, password = password, email = email)
        if new_user:
            db.session.add(new_user)
            db.session.commit()

            login_session["username"] = new_user.name

            flash(f'{username}! Register successfuly', 'success')
            return redirect(url_for('task.view_task'))
        
        return "Please enter requred data"
    return render_template("register.html")
        
@auth_bp.route('/logout')
def logout():

    if 'username' not in login_session:

        return redirect(url_for("auth.login"))
    
    login_session.pop('username')
    return redirect(url_for("auth.login"))

app/routes/tasks.py
from flask import Flask, Blueprint, redirect, render_template, url_for, request, flash, session as login_session
from app import db
from app.modules import Task

task_bp = Blueprint("task", __name__)

@task_bp.route('/', methods = ["POST", "GET"])
def view_task():
    if 'username' not in login_session:

        return redirect(url_for('auth.login'))
    
    tasks = Task.query.all()
    return render_template('home.html', tasks = tasks)

@task_bp.route('/add', methods = ["POST"])
def add():
    title = request.form.get("title")
    new_task = Task(title = title, status = "Pending")
    db.session.add(new_task)
    db.session.commit()
    return redirect(url_for('task.view_task'))

@task_bp.route("/clear", methods = ["POST"])
def clear():
    Task.query.delete()
    db.session.commit()
    flash("All task cleared!", "alert")
    return redirect(url_for('task.view_task'))

@task_bp.route("/toggle/<int:task_id>", methods = ["POST"])
def toggle(task_id):

    user = Task.query.get(task_id)
    if user.status == "Pending":
        user.status = "Working"
    elif user.status == "Working":
        user.status = "Done"
    else:
        user.status = "Pending"

    db.session.commit()
    return redirect(url_for('task.view_task'))

app/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Base html {% endblock %}</title>
    <link rel="stylesheet" href="{{ url_for('static', filename = 'css/style.css') }}">
</head>
<body>

    <dev class="container">
        <header>
            <h2>Welcome</h2>

            <nav>
                <a href="{{ url_for('task.view_task') }}">Home</a>
                <a href="{{ url_for('auth.login') }}">Login</a>
                <a href="{{ url_for('auth.logout') }}">Logout</a>
            </nav>
        </header>
    </dev>

    <div class="container">
        {% with messages = get_flashed_messages( with_categories = True) %}
            {% if messages %}
                {% for category, mess in messages %}
                    <div class="flash {{ category }}">{{mess}}</div>
                {% endfor %}
            {% endif %}
        {% endwith %}        
    </div>

    {% block content %}{% endblock %}
    
</body>
</html>

app/templates/home.html
{% extends "base.html" %}

{% block title %}Task page{% endblock %}

{% block content %}
    <div class="task-box">
        <h2>Task</h2>

        <form action="{{ url_for('task.add') }}" method="POST" class="task-form">

            <input type="text" name="title" placeholder="new Task">

            <button type="submit" class="btn">Add</button>

        </form>

        {% if tasks %}

            <form action="{{ url_for('task.clear') }}" method="POST">

                <button type="submit" class="btn btn-clear">Clear all tasks</button>

            </form>

            <br>
            <table class="task_table">
                <thead>
                    <tr>
                        <th class="col">Index</th>
                        <th class="col">Task</th>
                        <th class="col">Status</th>
                        <th class="col">Change</th>
                    </tr>
                </thead>

                <tbody>
                    {% for task in tasks %}

                    <tr>
                        <td>{{loop.index}}</td>
                        <td>{{task.title}}</td>
                        <td>
                            <span class="badge {{ task.status|lower }}">{{task.status}}</span>
                        </td>
                        <td>
                            <form action="{{ url_for('task.toggle', task_id = task.id) }}" method="POST">
                                <button type="submit" class="btn btn-smal">Next</button>
                            </form>
                        </td>
                    </tr>

                    {% endfor %}
                </tbody>
                
            </table>
        {% else %}
            <p>No task yet. Add one above!</p>
        {% endif %}
    </div>
{% endblock %}

app/templates/login.html
{% extends "base.html" %}

{% block title %}Login page{% endblock %}

{% block content %}
    <div class="login-box">

        <h2>Login</h2>

        <form action="{{ url_for('auth.login') }}" class="form-box" method="POST">

            <div class="form-group">

                <label for="name">Username</label>
                <input type="text" id="name" name="username" placeholder="enter Username" required>

            </div>
            
            <div class="form-group">

                <label for="pass">Password</label>
                <input type="password" id="pass" name="password" placeholder="enter password" required>

            </div>

            <button type="submit" class="btn">Login</button>                
        </form>
        
        <p>Don't have an account? <a href="{{ url_for('auth.register') }}"><span style="color: green;">Register</span></a></p>
    </div>
{% endblock %}

app/templates/register.html
{% extends "base.html" %}

{% block title %}Register page{% endblock %}

{% block content %}
    <div class="login-box">
        <h2>Register</h2>

        <form action="{{ url_for('auth.register') }}" class="register-box" method="POST">

            <div class="form-group">

                <label for="name">Username</label>
                <input type="text" id="name" name="username" placeholder="enter username" required>
                
            </div>

            <div class="form-group">

                <label for="pass">Password</label>
                <input type="password" id="pass" name="password" placeholder="enter password" required>

            </div>
        
            <div class="form-group">

                <label for="email">Email</label>
                <input type="email" id="email" name="email" placeholder="example@gmail.com" required>

            </div>

                <button type="submit" class="btn">Register</button>

        </form>
    </div>
{% endblock %}